### ISSUE TITLE
4.1表单处理

### ISSUE THREAD

**Issue by nikotung** [astaxie/build-web-application-with-golang#167]
我用4.1中的代码处理表单，如果访问的是http://localhost:9090就是正常了，但是访问http://localhost:9090/login这个就有问题了，后台打印日志如下：
2013/03/13 01:03:02 http: panic serving [::1]:49860: runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/pkg/net/http/server.go:589 (0x4bfd1)
    _func_004: buf.Write(debug.Stack())
/usr/local/go/src/pkg/runtime/proc.c:1443 (0xf73e)
    panic: reflect·call(d->fn, d->args, d->siz);
/usr/local/go/src/pkg/runtime/runtime.c:128 (0x100f5)
    panicstring: runtime·panic(err);
/usr/local/go/src/pkg/runtime/thread_darwin.c:410 (0x12ece)
    sigpanic: runtime·panicstring("invalid memory address or nil pointer dereference");
/usr/local/go/src/pkg/html/template/template.go:51 (0x306a7)
    (_Template).Execute: t.nameSpace.mu.Lock()
/Users/luosone/GoYard/gostudy/sourcecode/webForm/src/web/web.go:29 (0x25ea)
    login: t.Execute(w, nil)
/usr/local/go/src/pkg/net/http/server.go:703 (0x40e42)
    HandlerFunc.ServeHTTP: f(w, r)
/usr/local/go/src/pkg/net/http/server.go:941 (0x41a22)
    (_ServeMux).ServeHTTP: mux.handler(r).ServeHTTP(w, r)
/usr/local/go/src/pkg/net/http/server.go:669 (0x40c94)
    (*conn).serve: handler.ServeHTTP(w, w.req)
/usr/local/go/src/pkg/runtime/proc.c:271 (0xdc30)
    goexit: runtime·goexit(void)

**Comment by oknixus** [comment]
@astaxie 老师，您看下我这个错误：
https://play.golang.org/p/rgDrBPceMP
我的目录结构：
![image](https://cloud.githubusercontent.com/assets/4592706/16705621/449eeae2-45c2-11e6-821f-b6936cda272f.png)

**Comment by oknixus** [comment]
文件名已经改成英文了，但是错误还是一样的

**Comment by oknixus** [comment]
后台错误信息
![image](https://cloud.githubusercontent.com/assets/4592706/16705867/3a5cd424-45ca-11e6-8f40-37b64c329586.png)

**Comment by oknixus** [comment]
改来改去，还是这个错误，求老师指点

**Comment by cywmm** [comment]
@oknixus 我也遇到这个问题，如作者所说其实就是.html文件的路径没有找到

`t, _ := template.ParseFiles("src/login.html")`

 把路径写正确就行了~

**Comment by zaxcler** [comment]
同样遇到这个问题 打印了当前路径  是在我当前项目路径  login.html和 main.go在同一个目录下（都在src／myapp下面） 用的是mac系统

**Comment by z724211471** [comment]
emmm 我这样写就可以了 不知道为什么..
t, _ := template.ParseFiles("/Users/xxx/go/src/main/login.gtpl")

**Comment by lpwlpw** [comment]
命令行进去相应目录，go run 执行就可以了
