### ISSUE TITLE
string类型跟普通类型一样是值传递，不是引用传递

### ISSUE THREAD

**Issue by VFT** [astaxie/build-web-application-with-golang#331]
Go语言中string，slice，map这三种类型的实现机制类似指针，所以可以直接传递，而不用取地址后传递指针。（注：若函数需改变slice的长度，则仍需要取地址传递指针）

应该去掉string。

**Comment by Freshman585** [comment]
string的底层实现是这样的结构体，即使复制，也是复制一个byte类型的指针，和一个int变量
struct String
{
        byte*   str;
        intgo   len;
};
