### ISSUE TITLE
Compilation the book for web

### ISSUE THREAD

**Issue by vitkarpov** [astaxie/build-web-application-with-golang#448]
I didn't find a website with the book. Seems it's a good idea to build md files into html with on tope of some template to turn repo into website, so it could be more convenient to read it online.

Is there a website? It it's not, would you like to get a pull request with static generator like jekyll to build one?

**Comment by astaxie** [comment]
https://www.gitbook.com/book/astaxie/build-web-application-with-golang

**Comment by vitkarpov** [comment]
Great!
