### ISSUE TITLE
14.3 beego.Form还存在吗？

### ISSUE THREAD

**Issue by DeanSinaean** [astaxie/build-web-application-with-golang#459]
beego代码里没找到这个结构体

**Comment by astaxie** [comment]
这是表单验证http://beego.me/docs/mvc/controller/validation.md

这是表单处理和渲染
http://beego.me/docs/mvc/controller/params.md#%E7%9B%B4%E6%8E%A5%E8%A7%A3%E6%9E%90%E5%88%B0-struct
