### ISSUE TITLE
ubuntu apt-get install go

### ISSUE THREAD

**Issue by jdxin0** [astaxie/build-web-application-with-golang#475]
原来的方法好像装不了

Ubuntu是目前使用最多的Linux桌面系统，使用apt-get命令来管理软件包，我们可以通过下面的命令来安装Go，为了以后方便，应该把 git mercurial 也安装上：

sudo apt-get install python-software-properties
sudo add-apt-repository ppa:gophers/go
sudo apt-get update
sudo apt-get install golang-stable git-core mercurial

用以下方式安装成功
sudo apt-get install gccgo-go

**Comment by vCaesar** [comment]
This installation method is not good,Please use wget.
