### ISSUE TITLE
我用go执行shell命令的时候总是报错，麻烦帮我看下这是什么原因

### ISSUE THREAD

**Issue by lfq618** [astaxie/build-web-application-with-golang#536]
func getExifOrientation(picPath string) int {
        cmd := "/usr/bin/identify -format '%[exif:orientation]' " + picPath
        cmd = strings.TrimSuffix(cmd, "\n")
        fmt.Println(cmd)
        response, err := exec.Command(cmd).Output()

        if err != nil {
                panic(err)
        }
        identify, _ := strconv.Atoi(string(response))
        return identify
}

执行时的错误信息：
panic: fork/exec /usr/bin/identify -format '%[exif:orientation]' /da0/pic/pic_lfq618/2015/06/25/18/1001v1435226924788069166.jpg: no such file or directory

goroutine 1 [running]:
main.getExifOrientation(0x5547c0, 0x3e, 0x1)
	/home/goroot/src/gopictest/main.go:17 +0x2f1
main.main()
	/home/goroot/src/gopictest/main.go:44 +0x242
exit status 2

**Comment by anthonyfok** [comment]
好像要把要执行的应用程序和个别的命令行选项分开的哟……

你看，按你贴出来的代码，你的程序要去找的文件叫 "/usr/bin/identify -format '%[exif:orientation]' /da0/pic/pic_lfq618/2015/06/25/18/1001v1435226924788069166.jpg", 但这个 “文件” 当然不存在啦。

请参考 https://golang.org/pkg/os/exec/#Command ，记得展开该条目的  Example，有例子。

**Comment by lfq618** [comment]
哦，懂了，谢谢啦
