### ISSUE TITLE
PDF version has no figures?

### ISSUE THREAD

**Issue by yf13** [astaxie/build-web-application-with-golang#544]
It seems the PDF format e-book has no figures, see this screenshot:

![pdf-no-figure](https://cloud.githubusercontent.com/assets/5899566/9983680/b27708e4-6038-11e5-9abb-4922848978c5.png)

**Comment by astaxie** [comment]
where did you download the PDF version, I didn't provide any pdf version

**Comment by yf13** [comment]
I got it here: https://www.gitbook.com/book/astaxie/build-web-application-with-golang/details

**Comment by kennwhite** [comment]
*bump
By the way, if you were able to add the images to the pdf, you could even sell printed copies on Lulu.
:+1:

**Comment by vCaesar** [comment]
This can now be closed.
