### ISSUE TITLE
5.5 beedb 查询数据一节的例子2代码有误

### ISSUE THREAD

**Issue by alai04** [astaxie/build-web-application-with-golang#593]
照原文上的例子2：
var user2 Userinfo
orm.Where(3).Find(&user2) // 这是上面版本的缩写版，可以省略主键

查询不到数据，打开OnDebug可以看到：
SELECT Uid, Username, Departname, Created FROM userinfo WHERE `Id` = ? LIMIT 1
&{0xc208044960 userinfo 1 0 `Id` = ? [4]  Uid, Username, Departname, Created Uid    ` ? 2}

生成的SQL语句中的where子句是 `id` = ?
将代码修改为
orm.SetPK("uid").Where(3).Find(&user2)
可以正确查询到数据

在struct Userinfo中定义Uid为PK，只能对Save方法有效，似乎对Where和Find无效，有什么好方法吗？

**Comment by vCaesar** [comment]
This section will be rewritten.
