### ISSUE TITLE
go安装高版本的一个问题或者要求

### ISSUE THREAD

**Issue by dhqdqk** [astaxie/build-web-application-with-golang#665]
安装go1.5以上版本时，必须先安装一个1.4~1.5内的版本，然后才能升级到1.5以上
引用：

> You will need go1.4 installed before you can install go1.5 (since this is compiling from go source and 1.5 doesnt use C anymore) run gvm install go1.4 gvm use go1.4 export GOROOT_BOOTSTRAP=$GOROOT then run gvm install go1.5 . This should be fixed in pull #154 

ubuntu: 
sudo apt-get install golang-go

**Comment by vCaesar** [comment]
Not need it now,and update this section.
