### ISSUE TITLE
gvm安装golang报错，翻墙也不行，搜了很多了，没找到有效解决办法

### ISSUE THREAD

**Issue by oknixus** [astaxie/build-web-application-with-golang#667]
gvm listall

gvm gos (available)

fatal: unable to access 'https://go.googlesource.com/go/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received

**Comment by submind** [comment]
Could you try downloading the installer from link: https://golang.org/dl/ ? Does it work?

**Comment by oknixus** [comment]
@submind I had downloaded the installer from golang.org. Thanhs very much.

**Comment by jl-** [comment]
[hosts](https://github.com/racaljk/hosts/blob/master/hosts). 添加 golang 相关的 host 试试 @oknixus

**Comment by AL1994** [comment]
view it GitHub




------------------ 原始邮件 ------------------
发件人: "Nixus";<notifications@github.com>;
发送时间: 2016年6月10日(星期五) 上午9:08
收件人: "astaxie/build-web-application-with-golang"<build-web-application-with-golang@noreply.github.com>; 

主题: Re: [astaxie/build-web-application-with-golang] gvm安装golang报错，翻墙也不行，搜了很多了，没找到有效解决办法 (#667)




Closed #667.
