### ISSUE TITLE
Update GitBook

### ISSUE THREAD

**Issue by Oxyrus** [astaxie/build-web-application-with-golang#670]
The repository has been updated many times since the last edit on https://www.gitbook.com/book/astaxie/build-web-application-with-golang/details, it would be awesome to update the gitbook to use the last version of the book.

**Comment by hangim** [comment]
+1, It should be update

**Comment by victorgama** [comment]
@astaxie Any update on this?

**Comment by astaxie** [comment]
gitbook not support space. there's some issue with the gitbook.

**Comment by mistadikay** [comment]
Hey folks, so I made a [PR](https://github.com/astaxie/build-web-application-with-golang/issues/739) aiming to fix failing build for the English version. I'm sure there are other mistakes I didn't notice and also other languages are not fixed — so please help to fix versions for you native languages and let's update this great book on gitbook.io.

**Comment by mistadikay** [comment]
Hey @astaxie! Thanks for a quick response. Though, looks like the book on gitbook.io is not fully updated. Check this, for example: [05.3 on gitbook.io](https://astaxie.gitbooks.io/build-web-application-with-golang/content/en/05.3.html) and [05.3 on github](https://github.com/astaxie/build-web-application-with-golang/blob/master/en/05.3.md) are different:
> As a final note on this secton, there is a useful SQLite management tool available: http://sqliteadmin.orbmu2k.de/

vs

> As a final note on this section, there is a useful SQLite management tool available: http://sqlitebrowser.org

Can you please double-check? Thanks!

**Comment by astaxie** [comment]
let me check that in gitbook
