### ISSUE TITLE
4.1的例子不通，

### ISSUE THREAD

**Issue by wallace1110** [astaxie/build-web-application-with-golang#679]
go的版本1.6.2
显示不了login.gtpl

method: GET
2016/06/07 14:35:20 http: panic serving 127.0.0.1:60379: runtime error: invalid memory address or nil pointer dereference
goroutine 4 [running]:
net/http.(*conn).serve.func1(0xc820130a80)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x39d520, 0xc82000a100)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:79 +0x3c
html/template.(*Template).Execute(0x0, 0x1240158, 0xc820077ee0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:101 +0x34

**Comment by zjutjsj1004** [comment]
是不是你的gtpl相对路径有问题
