### ISSUE TITLE
Acknowledgments?

### ISSUE THREAD

**Issue by LarryBattle** [astaxie/build-web-application-with-golang#692]
您可以加我和Unknwon吗？
Could you re-add [Unknwon](https://github.com/Unknwon) and myself to the Acknowledgments?
For some odd reason it was deleted in this commit [here](https://github.com/astaxie/build-web-application-with-golang/commit/0461f48affa57c3d366e7a090a35a23e552e26a7#diff-acca2a2774392000da79efcaff91ee3cL8).

The English version was mostly translated by [Unknwon](https://github.com/Unknwon) and [myself](https://github.com/LarryBattle) back in 2013.
Also I wrote up the [code section](https://github.com/Unknwon/build-web-application-with-golang_EN/tree/master/code). I wish I finished but ran out of time. :-)

- Reference: https://github.com/Unknwon/build-web-application-with-golang_EN/
@Unknwon

**Comment by astaxie** [comment]
@LarryBattle sorry to forget to add the Acknowledgments into the repo. I want to add a Acknowledgments for all translators for this book.  Not only for English or the other one.  Long time no maintain this repo. I also think need to upgrade many content now. The same case like you I also ran out of time. 😃

**Comment by astaxie** [comment]
https://github.com/astaxie/build-web-application-with-golang/commit/b9dbf79fcb001f6dff1682a5b1100839a5b89fe1
