### ISSUE TITLE
老师好！这里的注释有些看不懂

### ISSUE THREAD

**Issue by oknixus** [astaxie/build-web-application-with-golang#695]
![image](https://cloud.githubusercontent.com/assets/4592706/17793550/d4acea52-65da-11e6-998c-d40e7e976e70.png)

这里是为了说明是主键的，对吗？

**Comment by oknixus** [comment]
在 [5.5 使用 beedb库进行 orm 开发](https://astaxie.gitbooks.io/build-web-application-with-golang/content/zh/05.5.html)

**Comment by tudo666** [comment]
默认表的主键的Id 字段，但是如果表的主键不是Id字段的话，需要用tag进行标注

**Comment by oknixus** [comment]
@tudo666 这里说的，Uid 不是主键？

**Comment by submind** [comment]
@oknixus I think it means that this property is used as primary key in the application though it's actually not the primary key of db table.

**Comment by oknixus** [comment]
@submind thx
