### ISSUE TITLE
Do you want a PR?

### ISSUE THREAD

**Issue by thewhitetulip** [astaxie/build-web-application-with-golang#702]
I have adapted the chapter on Go basics from your book into my book, have modified a lot of things, I'd be happy to send over a PR, please take a look and let me know.

As per the license, have added the attribution to the readme, please do let me know if you require more attribution.

https://github.com/thewhitetulip/web-dev-golang-anti-textbook/blob/master/manuscript/02.1IntroductionGo.md

02.2VariablesDataStruct.md
02.3CntrlStmtFunctions.md
02.4Struct.md
02.5ObjectOriented.md
02.6Interface.md
02.7Concurrency.md

Also thank you for writing this book!

**Comment by vCaesar** [comment]
If it's a good idea,Please do it.

**Comment by thewhitetulip** [comment]
How do you want it? Shall I submit the above mentioned chapters verbatim?

**Comment by astaxie** [comment]
@thewhitetulip nice book and updated. I think you can keep update in your book.

**Comment by thewhitetulip** [comment]
@astaxie Thanks :-) Your book was the inspiration! I'll send a PR based on the updated chapters and will make modifications as per your review comments.

**Comment by astaxie** [comment]
@thewhitetulip that's cool. thanks for your keeping update.

**Comment by thewhitetulip** [comment]
@astaxie @vCaesar Please review the PR.
