### ISSUE TITLE
中文那边好像很多文件都乱了

### ISSUE THREAD

**Issue by headwindfly** [astaxie/build-web-application-with-golang#721]
https://github.com/astaxie/build-web-application-with-golang/tree/master/zh

是因为合并问题吗？

比如：
02.0.md~HEAD	
02.0.md~eead24cf064976b648de58
...
02.3.md~HEAD	
02.3.md~eead24cf064976b648de5826eab51880c803b0fa	
02.4.md~HEAD
02.4.md~eead24cf064976b648de5826eab51880c803b0fa	
....

**Comment by headwindfly** [comment]
这个导致目录的连接大部分失效了，希望有空修复一下

**Comment by zhong518** [comment]
好像是修复了

**Comment by astaxie** [comment]
嗯，刚才已经修复了，之前merge了一个PR，导致了这个问题
