### ISSUE TITLE
Add syntax highlighting to code examples

### ISSUE THREAD

**Issue by mistadikay** [astaxie/build-web-application-with-golang#741]
Hey!

I noticed that code examples in this book don't use code highlighting, so I was wondering is there a particular reason for that? Otherwise it's pretty easy to fix it by using ` ```go ` and ` ``` ` tags. 

Compare these before/after examples:
![screenshot 2016-11-20 11 40 32](https://cloud.githubusercontent.com/assets/742056/20462192/2eaa3530-af16-11e6-820b-8d173352b06f.png)
vs
![screenshot 2016-11-20 11 40 37](https://cloud.githubusercontent.com/assets/742056/20462191/2ea8a81e-af16-11e6-86d2-2a3de1788b90.png)

**Comment by vCaesar** [comment]
I know easy to fix,But very boring.
