### ISSUE TITLE
runtime.GOMAXPROCS  默认不是1， 应该是当前逻辑CPU核数，应该修改一下

### ISSUE THREAD

**Issue by junneyang** [astaxie/build-web-application-with-golang#761]
![image](https://cloud.githubusercontent.com/assets/6802322/21419232/716df9e2-c861-11e6-94aa-99c1b99b49f5.png)

可以通过 runtime.GOMAXPROCS(-1) 验证:
![image](https://cloud.githubusercontent.com/assets/6802322/21419258/933210b8-c861-11e6-977d-5df0ae54e58d.png)

**Comment by vCaesar** [comment]
Go 1.5 changed it,I will update it.
