### ISSUE TITLE
`extra expression in const declaration`

### ISSUE THREAD

**Issue by fengzhihao123** [astaxie/build-web-application-with-golang#781]
你好
我在学习2.2 GO基础这一章节的时候
该段代码报错: `extra expression in const declaration`
 const （
        a = iota    a=0
        b = "B"
        c = iota    //c=2
        d,e,f = iota,iota,iota //d=3,e=3,f=3
        g //g = 4
    ）

**Comment by vCaesar** [comment]
Please see [#782](https://github.com/astaxie/build-web-application-with-golang/pull/782)

**Comment by fengzhihao123** [comment]
think you.
