### ISSUE TITLE
There is a mistake about reference types in English Version

### ISSUE THREAD

**Issue by ZhenhangTung** [astaxie/build-web-application-with-golang#793]
In Chapter [Control statements and functions](https://astaxie.gitbooks.io/build-web-application-with-golang/content/en/02.3.html)， there is a mistake in this bullet point:

> ```string```, ```slice``` and ```map``` are reference types, so they use pointers when passing to functions by default. (Attention: If you need to change the length of ```slice```, you have to pass pointers explicitly)

I believe ```string``` is not a reference type. Instead, I believe it should be ```channel```. In Chinese ver, this one is correct.
Here are some references:

- https://forum.golangbridge.org/t/reference-types-slices/1444
- https://groups.google.com/forum/#!topic/golang-nuts/xQUsmdo6oSs

My PR is [this one](https://github.com/astaxie/build-web-application-with-golang/pull/794).

**Comment by vCaesar** [comment]
There are only three types of golang that are copied to the memory address,`channel`, `slice` and `map`.

**Comment by vCaesar** [comment]
There Are No Reference Types in Golang.

**Comment by ZhenhangTung** [comment]
> There Are No Reference Types in Golang

I'm kind of confused about it. I've done some searches, and I found that in this [commit](https://github.com/golang/go/commit/b34f0551387fcf043d65cd7d96a0214956578f94), the Golang group change the definition of a slice. So why they changed this?
