### ISSUE TITLE
2.7 goroutines example has problem

### ISSUE THREAD

**Issue by isNeilLin** [astaxie/build-web-application-with-golang#950]
I tried goroutines example like this:
```go
package main

import (
	"fmt"
	"runtime"
)

func say(s string) {
	for i:=0; i<5; i++ {
		runtime.Gosched()
		fmt.Println(s)
	}
}

func main() {
	go say("Golang") //开一个新的Goroutine执行
	say("hello") //当前Goroutine执行
}
```
only output:
```
hello
hello
hello
hello
hello
```
I tried use `time.Sleep(100*time.Millisecond)` instead of `runtime.Gosched()` and it works. 
Is `runtime.Gosched()` has any problem now?
 My golang version is `go1.9.1`, My platform is `darwin/amd64`

**Comment by Dracozny** [comment]
The tutorial is older. I found adding runtime.GOMAXPROCS(1) to func Main() resolved this
`package main

import (
	"fmt"
	"runtime"
)

func say(s string) {
	for i := 0; i < 5; i++ {
		runtime.Gosched()
		fmt.Println(s)
	}
}

func main() {
	runtime.GOMAXPROCS(1)
	go say("Golang") //开一个新的Goroutine执行
	say("hello")     //当前Goroutine执行
}`
