### ISSUE TITLE
Typo on 02.2 - "Define by group"

### ISSUE THREAD

**Issue by criscola** [astaxie/build-web-application-with-golang#958]
Hello. I noticed a typo on 02.2 chapter, under "Define by group" section. 

> Unless you assign the value of constant is iota, [...]

I think it should be something more like "Unless the assignment of the constant value is iota, [...]"

Best regards

**Comment by ccsay** [comment]
您好，您发的邮件已收到。我会尽快阅读。

**Comment by Allen-Jaeger** [comment]
这是来自QQ邮箱的自动回复邮件。您的邮件，我已经收到，O(∩_∩)O谢谢
