### ISSUE TITLE
已购买Kindle书，仅为表示感谢。

### ISSUE THREAD

**Issue by sirius1024** [astaxie/build-web-application-with-golang#966]
感谢作者免费、开源的精神，这些资料对于我有非常大的帮助。
虽然我可以在Gitbook上阅读最新最全的资料，但仍然购买了Kindle电子版的书，仅仅对作者的辛苦努力和奉献表示感谢。

**Comment by dreamer2q** [comment]
习惯了在kindle上面看书，在寻找kindle的资源，不过下载的pdf或者epub全都是没有图片的。
不知道能否分享一下kindle书籍？
